name = "toubarreplace"
compatibility_date = "2026-09-01"

[assets]
directory = "./out"
html_handling = "auto-trailing-slash"
not_found_handling = "404-page"

[[routes]]
pattern = "toubarreplace.z-agent.ccwu.cc"
custom_domain = true
